# Lesson 2: Intro to NumPy

Our Second top 5 Library is NumPy. NumPY is a package that provides support for multi-dimensional arrays and matrices, along with mathematical functions to operate on them. NumPy is short for Numerical Python.

Numpy is an open source library for Scientific Computing in python. It provides support for multi-dimensional arrays and matrices, along with efficient mathematical functions for operating on these arrays.

An array is a ordered list/ sequenced collection of elements with same datatype, just group of similar data.

Comments

The Python comment character is '#': anything after '#' on the line is ignored by the Python interpreter. .

Multi-line strings can be used within code blocks to provide multi-line comments.

Multi-line strings are delimited by pairs of triple quotes (''' or """). Any newlines in the string will be represented as '\n' characters in the string.

Keep in mind I've left out most of the comments in the code for the course. You should be able to commen the code after you run the cell. If you can't find the answer then use Google.

In [3]:
import numpy as np
x = np.array([1,2,3,4,5])
x

array([1, 2, 3, 4, 5])

In [4]:
type(x)

numpy.ndarray

In [5]:
x.ndim

1

In [6]:
x.shape

(5,)

In [7]:
len(x)

5

In [8]:
x.size

5

In [9]:
x.dtype

dtype('int64')

In [10]:
x

array([1, 2, 3, 4, 5])

In [11]:
x[0,]

1

In [12]:
x[4,]

5

In [13]:
x[:3]

array([1, 2, 3])